all : lineas_1.txt lineas_2.txt

lineas_1.txt : numeros.txt lineas.py
	python lineas.py

lineas_2.txt : numeros.txt lineas.py
	python lineas.py

numeros.x : numeros.c	
	gcc numeros.c -o numeros.txt

numeros.txt: numeros.x
	./numeros.x > numeros.txt 


